<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvinciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $provincias =[
            ['1','BAGUA'],
            ['1','BONGARA'],
            ['1','CHACHAPOYAS'],
            ['1','CONDORCANQUI'],
            ['1','LUYA'],
            ['1','RODRIGUEZ DE MENDOZA'],
            ['1','UTCUBAMBA'],
            ['2','AIJA'],
            ['2','ANTONIO RAYMONDI'],
            ['2','ASUNCION'],
            ['2','BOLOGNESI'],
            ['2','CARHUAZ'],
            ['2','CARLOS FERMIN FITZCARRALD'],
            ['2','CASMA'],
            ['2','CORONGO'],
            ['2','HUARAZ'],
            ['2','HUARI'],
            ['2','HUARMEY'],
            ['2','HUAYLAS'],
            ['2','MARISCAL LUZURIAGA'],
            ['2','OCROS'],
            ['2','PALLASCA'],
            ['2','POMABAMBA'],
            ['2','RECUAY'],
            ['2','SANTA'],
            ['2','SIHUAS'],
            ['2','YUNGAY'],
            ['3','ABANCAY'],
            ['3','ANDAHUAYLAS'],
            ['3','ANTABAMBA'],
            ['3','AYMARAES'],
            ['3','CHINCHEROS'],
            ['3','COTABAMBAS'],
            ['3','GRAU'],
            ['4','AREQUIPA'],
            ['4','CAMANA'],
            ['4','CARAVELI'],
            ['4','CASTILLA'],
            ['4','CAYLLOMA'],
            ['4','CONDESUYOS'],
            ['4','ISLAY'],
            ['4','LA UNION'],
            ['5','CANGALLO'],
            ['5','HUAMANGA'],
            ['5','HUANCA SANCOS'],
            ['5','HUANTA'],
            ['5','LA MAR'],
            ['5','LUCANAS'],
            ['5','PARINACOCHAS'],
            ['5','PAUCAR DEL SARA SARA'],
            ['5','SUCRE'],
            ['5','VICTOR FAJARDO'],
            ['5','VILCAS HUAMAN'],
            ['6','CAJABAMBA'],
            ['6','CAJAMARCA'],
            ['6','CELENDIN'],
            ['6','CHOTA'],
            ['6','CONTUMAZA'],
            ['6','CUTERVO'],
            ['6','HUALGAYOC'],
            ['6','JAEN'],
            ['6','SAN IGNACIO'],
            ['6','SAN MARCOS'],
            ['6','SAN MIGUEL'],
            ['6','SAN PABLO'],
            ['6','SANTA CRUZ'],
            ['7','CALLAO'],
            ['8','ACOMAYO'],
            ['8','ANTA'],
            ['8','CALCA'],
            ['8','CANAS'],
            ['8','CANCHIS'],
            ['8','CHUMBIVILCAS'],
            ['8','CUSCO'],
            ['8','ESPINAR'],
            ['8','LA CONVENCION'],
            ['8','PARURO'],
            ['8','PAUCARTAMBO'],
            ['8','QUISPICANCHI'],
            ['8','URUBAMBA'],
            ['9','ACOBAMBA'],
            ['9','ANGARAES'],
            ['9','CASTROVIRREYNA'],
            ['9','CHURCAMPA'],
            ['9','HUANCAVELICA'],
            ['9','HUAYTARA'],
            ['9','TAYACAJA'],
            ['10','AMBO'],
            ['10','DOS DE MAYO'],
            ['10','HUACAYBAMBA'],
            ['10','HUAMALIES'],
            ['10','HUANUCO'],
            ['10','LAURICOCHA'],
            ['10','LEONCIO PRADO'],
            ['10','MARAÑON'],
            ['10','PACHITEA'],
            ['10','PUERTO INCA'],
            ['10','YAROWILCA'],
            ['11','CHINCHA'],
            ['11','ICA'],
            ['11','NASCA'],
            ['11','PALPA'],
            ['11','PISCO'],
            ['12','CHANCHAMAYO'],
            ['12','CHUPACA'],
            ['12','CONCEPCION'],
            ['12','HUANCAYO'],
            ['12','JAUJA'],
            ['12','JUNIN'],
            ['12','SATIPO'],
            ['12','TARMA'],
            ['12','YAULI'],
            ['13','ASCOPE'],
            ['13','BOLIVAR'],
            ['13','CHEPEN'],
            ['13','GRAN CHIMU'],
            ['13','JULCAN'],
            ['13','OTUZCO'],
            ['13','PACASMAYO'],
            ['13','PATAZ'],
            ['13','SANCHEZ CARRION'],
            ['13','SANTIAGO DE CHUCO'],
            ['13','TRUJILLO'],
            ['13','VIRU'],
            ['14','CHICLAYO'],
            ['14','FERREÑAFE'],
            ['14','LAMBAYEQUE'],
            ['15','BARRANCA'],
            ['15','CAJATAMBO'],
            ['15','CANTA'],
            ['15','CAÑETE'],
            ['15','HUARAL'],
            ['15','HUAROCHIRI'],
            ['15','HUAURA'],
            ['15','LIMA'],
            ['15','OYON'],
            ['15','YAUYOS'],
            ['16','ALTO AMAZONAS'],
            ['16','DATEM DEL MARAÑON'],
            ['16','LORETO'],
            ['16','MARISCAL RAMON CASTILLA'],
            ['16','MAYNAS'],
            ['16','PUTUMAYO'],
            ['16','REQUENA'],
            ['16','UCAYALI'],
            ['17','MANU'],
            ['17','TAHUAMANU'],
            ['17','TAMBOPATA'],
            ['18','GENERAL SANCHEZ CERRO'],
            ['18','ILO'],
            ['18','MARISCAL NIETO'],
            ['19','DANIEL ALCIDES CARRION'],
            ['19','OXAPAMPA'],
            ['19','PASCO'],
            ['20','AYABACA'],
            ['20','HUANCABAMBA'],
            ['20','MORROPON'],
            ['20','PAITA'],
            ['20','PIURA'],
            ['20','SECHURA'],
            ['20','SULLANA'],
            ['20','TALARA'],
            ['21','AZANGARO'],
            ['21','CARABAYA'],
            ['21','CHUCUITO'],
            ['21','EL COLLAO'],
            ['21','HUANCANE'],
            ['21','LAMPA'],
            ['21','MELGAR'],
            ['21','MOHO'],
            ['21','PUNO'],
            ['21','SAN ANTONIO DE PUTINA'],
            ['21','SAN ROMAN'],
            ['21','SANDIA'],
            ['21','YUNGUYO'],
            ['22','BELLAVISTA'],
            ['22','EL DORADO'],
            ['22','HUALLAGA'],
            ['22','LAMAS'],
            ['22','MARISCAL CACERES'],
            ['22','MOYOBAMBA'],
            ['22','PICOTA'],
            ['22','RIOJA'],
            ['22','SAN MARTIN'],
            ['22','TOCACHE'],
            ['23','CANDARAVE'],
            ['23','JORGE BASADRE'],
            ['23','TACNA'],
            ['23','TARATA'],
            ['24','CONTRALMIRANTE VILLAR'],
            ['24','TUMBES'],
            ['24','ZARUMILLA'],
            ['25','ATALAYA'],
            ['25','CORONEL PORTILLO'],
            ['25','PADRE ABAD'],
            ['25','PURUS']
        ];
        foreach( $provincias as $prov){
            DB::table('provincias')->insert(['idDepartamento'=>$prov[0],'Provincia'=>$prov[1]]);
        }
    }
}
